[project]
name = "multi-tenant-booking-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yasin Amirany", email = "yasin.amirany@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "celery>=5.6.3",
    "django>=6.1",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "psycopg2-binary>=2.9.12",
    "redis>=8.1.0",
    "stripe>=15.5.0",
]

[project.scripts]
multi-tenant-booking-api = "multi_tenant_booking_api:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
]
